// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PtttApi.Db;

#nullable disable

namespace PtttApi.Migrations
{
    [DbContext(typeof(TenantContext))]
    [Migration("20231112211511_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PtttApi.Db.Entities.RoomieEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roomies");
                });

            modelBuilder.Entity("PtttApi.Db.Entities.TraitEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TraitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Traits");
                });

            modelBuilder.Entity("RoomieEntityTraitEntity", b =>
                {
                    b.Property<Guid>("RoomiesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TraitsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoomiesId", "TraitsId");

                    b.HasIndex("TraitsId");

                    b.ToTable("RoomieEntityTraitEntity");
                });

            modelBuilder.Entity("RoomieEntityTraitEntity", b =>
                {
                    b.HasOne("PtttApi.Db.Entities.RoomieEntity", null)
                        .WithMany()
                        .HasForeignKey("RoomiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PtttApi.Db.Entities.TraitEntity", null)
                        .WithMany()
                        .HasForeignKey("TraitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
